application: minuttihello
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: static

- url: /.*
  upload: postMessagePortal.html
  static_files: postMessagePortal.html
